Feature/ordinal days
acstech/liquid pull request #10
Opened 2017-01-11 20:41 UTC by ianmburns

@joshua We want to add a broader range of support to the date filter. There are a few features we would like to implement:

More date formats. See the timeInputFormats array. And the ability to specify an incoming date format string if it's not in the list of supported types.

Adding an hourly 'offset' option to adjust the date time to a different timezone

Adding the ability to specify an ordinal format for the day. So you can say 1st or 2nd. We wanted to keep the strftime implementation as close to the source as possible, so this is done before hand by replacing the key %0 with the appropriate ordinal phrase and day modifier.

2017-01-16 13:31 UTC, chrisnesbit1 approved these changes
@ianmburns LGTM

2017-01-17 14:51 UTC, mgolus requested changes

2017-01-17 14:51 UTC, mgolus commented on filters/date.go
> +	default:
I would argue that additional parameters after 3 should just be ignored if for some reason someone accidentally passes something additional in, and that the noop should only be when there are no parameters.

2017-01-17 15:41 UTC, ianmburns commented
@mgolus I've updated the code to reflect your suggestion.

2017-01-17 15:41 UTC, mgolus approved these changes

2017-01-17 15:41 UTC, merged